sudo: false
language: node_js
node_js:
  - "stable"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
install:
  - CC=gcc-5 CXX=g++-5 npm install
  - CC=gcc-5 make -f c-examples.makefile
script:
  - uname -a
  